testCore/Models/Account/ApplicationUser.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace testCore.Models.Account
{
    public class ApplicationUser : IdentityUser
    {
        [MaxLength(70)]
        [Required]
        public string FirstName { get; set; }

        [MaxLength(70)]
        public string LastName { get; set; }
    }
}

testCore/Models/ErrorViewModel.cs
using System;

namespace testCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

testCore/Models/SkiCard.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace testCore.Models
{
    public class SkiCard
    {
        public int Id { get; set; }
        public string ApplicationUserId { get; set; }
        public DateTime CreateOn { get; set; }
        
        [MaxLength(70)]
        [Required]
        public string CardHolderFirstName { get; set; }

        [MaxLength(70)]
        public string CardHolderLastName { get; set; }

        public DateTime CardHolderBirthDate { get; set; }

        [Phone]
        public string CardHolderPhoneNumber { get; set; }
    }
}

testCore/ViewModels/CreateSkiCardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace testCore.ViewModels
{
    public class CreateSkiCardViewModel
    {
        [DisplayName("Phone Number")]
        public string CardHolderPhoneNumber {get;set;}
        [DisplayName("First Name")]
        public string CardHolderFirstName { get;set;}
        [DisplayName("Last Name")]
        public string CardHolderLastName { get;set;}
        [DisplayName("Birth Date")]
        public DateTime CardHolderBirthDate { get;set;}
    }
}

testCore/ViewModels/EditSkiCardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace testCore.ViewModels
{
    public class EditSkiCardViewModel
    {
        public int Id { get; set; }
        public string CardHolderFirstName { get; set; }
        public string CardHolderLastName { get; set; }
        public DateTime CardHolderBirthDate { get; set; }
        public string CardHolderPhoneNumber { get; set; }
    }
}

testCore/ViewModels/SkiCardListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace testCore.ViewModels
{
    public class SkiCardListViewModel
    {
        public int Id { get; set; }
        public string CardHolderName { get; set; }
    }
}

testCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using testCore.Models;

namespace testCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

testCore/Controllers/SkiCardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using testCore.Data;
using testCore.Models;
using testCore.Models.Account;
using testCore.ViewModels;

namespace testCore.Controllers
{
    [Authorize]
    public class SkiCardController : Controller
    {
        private readonly SkiCardContext _skiCardContext;
        private readonly UserManager<ApplicationUser> _userManager;

        public SkiCardController(SkiCardContext skiCardContext, 
            UserManager<ApplicationUser> userManager)
        {
            _skiCardContext = skiCardContext;
            _userManager = userManager;
        }

        // GET: SkiCard
        public async Task<ActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            var skiCardViewModels = await _skiCardContext.SkiCards
                .Where(s => s.ApplicationUserId == userId)
                .Select(s => new SkiCardListViewModel
                {
                    Id = s.Id,
                    CardHolderName = s.CardHolderFirstName + " " +s.CardHolderLastName
                })
                .ToListAsync();
            return View(skiCardViewModels);
        }

        // GET: SkiCard/Create
        public async Task<ActionResult> Create()
        {
            var userId = _userManager.GetUserId(User);
            var currentUser = await _userManager.FindByEmailAsync(userId);
            var viewModel = new CreateSkiCardViewModel 
            {
                CardHolderPhoneNumber = currentUser.PhoneNumber
            };

            var hasExistingSkiCards = _skiCardContext.SkiCards.Any(s =>
            s.ApplicationUserId == userId);

            if (!hasExistingSkiCards)
            {
                viewModel.CardHolderFirstName = currentUser.FirstName;
                viewModel.CardHolderLastName = currentUser.LastName;
            }
            return View(viewModel);
        }

        // POST: SkiCard/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateSkiCardViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);

                SkiCard skiCard = new SkiCard
                {
                    ApplicationUserId = userId,
                    CreateOn = DateTime.UtcNow,
                    CardHolderFirstName = viewModel.CardHolderFirstName,
                    CardHolderLastName = viewModel.CardHolderLastName,
                    CardHolderBirthDate = viewModel.CardHolderBirthDate,
                    CardHolderPhoneNumber = viewModel.CardHolderPhoneNumber
                };

                _skiCardContext.SkiCards.Add(skiCard);
                await _skiCardContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(viewModel);
        }

        // GET: SkiCard/Edit/id
        public async Task<ActionResult> Edit(int id)
        {
            var userId = _userManager.GetUserId(User);
            var skiCardViewModel = await _skiCardContext.SkiCards
                .Where(s => s.ApplicationUserId == userId && s.Id == id)
                .Select(s => new EditSkiCardViewModel {
                    Id = s.Id,
                    CardHolderFirstName = s.CardHolderFirstName,
                    CardHolderLastName = s.CardHolderLastName,
                    CardHolderBirthDate = s.CardHolderBirthDate,
                    CardHolderPhoneNumber = s.CardHolderPhoneNumber
                }).SingleOrDefaultAsync();
            if(skiCardViewModel == null)
            {
                return NotFound();
            }

            return View(skiCardViewModel);
        }

        // POST: SkiCard/Edit/id
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(EditSkiCardViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var userId = _userManager.GetUserId(User);
                var skiCard = await _skiCardContext.SkiCards
                    .SingleOrDefaultAsync(s => s.ApplicationUserId == userId && s.Id == viewModel.Id);
                if(skiCard == null)
                {
                    return NotFound();
                }

                skiCard.CardHolderFirstName = viewModel.CardHolderFirstName;
                skiCard.CardHolderLastName = viewModel.CardHolderLastName;
                skiCard.CardHolderBirthDate = viewModel.CardHolderBirthDate.Date;
                skiCard.CardHolderPhoneNumber = viewModel.CardHolderPhoneNumber;

                await _skiCardContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viewModel);
        }
    }
}

testCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

testCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - testCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">testCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SkiCard" asp-action="Index">SkiCardList</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - testCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

testCore/Views/SkiCard/Create.cshtml
@model testCore.ViewModels.CreateSkiCardViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CreateSkiCardViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CardHolderPhoneNumber" class="control-label"></label>
                <input asp-for="CardHolderPhoneNumber" class="form-control" />
                <span asp-validation-for="CardHolderPhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardHolderFirstName" class="control-label"></label>
                <input asp-for="CardHolderFirstName" class="form-control" />
                <span asp-validation-for="CardHolderFirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardHolderLastName" class="control-label"></label>
                <input asp-for="CardHolderLastName" class="form-control" />
                <span asp-validation-for="CardHolderLastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CardHolderBirthDate" class="control-label"></label>
                <input asp-for="CardHolderBirthDate" class="form-control" />
                <span asp-validation-for="CardHolderBirthDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

testCore/Views/SkiCard/Index.cshtml
@model IEnumerable<testCore.ViewModels.SkiCardListViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CardHolderName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CardHolderName)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>